### ISSUE TITLE
unexpected token . at credleLoader.css:1

### ISSUE THREAD

**Issue by nik72619c** [mhnpd/react-loader-spinner#36]
After installing the npm package and using it in my component tree, I get the message:- 
```Unexpected token .
/Users/apple/codebase/avenue/node_modules/react-loader-spinner/dist/loader/css/CradleLoader.css:1
.react-spinner-loader-swing div {
^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at /Users/apple/codebase/avenue/node_modules/react-loader-spinner/dist/loader/CradleLoader.js:5:40
    at Object.<anonymous> (/Users/apple/codebase/avenue/node_modules/react-loader-spinner/dist/loader/CradleLoader.js:13:3)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at /Users/apple/codebase/avenue/node_modules/react-loader-spinner/dist/index.js:5:434
    at Object.<anonymous> (/Users/apple/codebase/avenue/node_modules/react-loader-spinner/dist/index.js:13:3)```

**Comment by nik72619c** [comment]
i don't think there should be any error thrown here...

**Comment by withgallantry** [comment]
I get the same also

**Comment by prKassad** [comment]
Same error on SSR mode. Module is not isomorphic?

**Comment by fajaman** [comment]
getting the same error

**Comment by dipta007** [comment]
getting the same error :(

**Comment by mhnpd** [comment]
In the newer version ``` 3.0.0 ```  import required css as follow:
``` import "react-loader-spinner/dist/loader/css/react-spinner-loader.css" ```

Older version:
Configure webpack as to read css as : ``` test: /\.scss$/ to test: /\.s?css$/ ```
